version: 2
jobs:
  build: # name of your job
    machine: true
    steps:
      - checkout
      - run:
          name: Deployment
          command: |
            docker build --rm=false -t trybe-backend .
            docker login --username=$HEROKU_EMAIL  --password=$HEROKU_API_KEY registry.heroku.com
            docker tag trybe-backend:latest registry.heroku.com/vast-plains-42829/web
            docker push registry.heroku.com/vast-plains-42829/web
            WEB_DOCKER_IMAGE_ID=$(docker inspect trybe-backend --format={{.Id}})
            echo "export WEB_DOCKER_IMAGE_ID" >> $BASH_ENV
            curl -n -X PATCH https://api.heroku.com/apps/trybe-backend/formation \
              -d '{
              "updates": [
                {
                  "type": "web",
                  "docker_image": "'"$(docker inspect registry.heroku.com/vast-plains-42829/web --format={{.Id}})"'"
                }
              ]}' \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $YOUR_HEROKU_API_KEY"

      - run:
          name: "What was my custom environment variable?"
          command: echo $(docker inspect trybe-backend --format={{.Id}})
      - run:
          name: "What was my custom environment variable +++++++?"
          command: echo $WEB_DOCKER_IMAGE_ID

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
