version: 2
jobs:
  build: # name of your job
    machine: true
    steps:
      - checkout
      - run:
          name: Deployment
          command: |
            docker build --rm=false -t trybe-backend .
            docker login --username=$HEROKU_EMAIL  --password=$HEROKU_API_KEY registry.heroku.com
            docker tag trybe-backend:latest registry.heroku.com/vast-plains-42829/web
            docker push registry.heroku.com/vast-plains-42829/web
            # export WEB_DOCKER_IMAGE_ID=$(eval echo WEB_DOCKER_IMAGE_ID=$(eval echo docker inspect trybe-backend --format={{.Id}})) >> $BASH_ENV
            echo "export WEB_DOCKER_IMAGE_ID=${eval echo docker inspect trybe-backend --format={{.Id}}}" >> $BASH_ENV
      - run:
          name: "What was my custom environment variable?"
          command: echo ${docker inspect trybe-backend --format={{.Id}}}
      - run:
          name: "What was my custom environment variable?"
          command: echo ${WEB_DOCKER_IMAGE_ID}

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            branches:
              only: develop
